package com.swm.enums;

public enum BookingStatus {
	// start - pending
	BOOKING_PENDING,
	BOOKING_PENDING_ALERT_SENT,
	// end - pending
	//BOOKING_PENDING_DEPOSIT,
	BOOKING_ACCEPTED,
	BOOKING_REJECTED,
	BOOKING_CANCELED,
	// start - pending-check-in
	BOOKING_PENDING_CHECKIN,
	BOOKING_PENDING_CHECKIN_REMAIN_SENT,
	BOOKING_PENDING_CHECKIN_APPOINTMENT_SENT,
	// end - pending-check-in
	// start - check-in
	BOOKING_CONFIRM_CHECKIN,
	BOOKING_CHECKIN_BY_PASSENGER_RELATIVE,
	BOOKING_CHECKIN_BY_LANDLORD,
	// end - check-in
	
	BOOKING_PENDING_CHECKOUT,
	// start - check-out
	BOOKING_CONFIRM_CHECKOUT,
	BOOKING_CHECKOUT_BY_LANDLORD,
	BOOKING_CHECKOUT_BY_PASSENGER_RELATIVE,
	// start - check-in
	BOOKING_FINISHED
}

