package com.swm.enums;

public enum BookingStatus {
	BOOKING_PENDING,
	BOOKING_PENDING_DEPOSIT,
	BOOKING_ACCEPTED,
	BOOKING_REJECTED,
	BOOKING_CANCLED,
	BOOKING_PENDING_CHECKIN,
	BOOKING_CONFIRM_CHECKIN,
	BOOKING_CHECKIN_BY_PASSENGER_RELATIVE,
	BOOKING_CHECKIN_BY_LANDLORD,
	BOOKING_PENDING_CHECKOUT,
	BOOKING_CONFIRM_CHECKOUT,
	BOOKING_FINISHED
}
