package com.swm.enums;

public enum HomestayStatus {
	HOMESTAY_REQUEST_PENDING,
	HOMESTAY_BOOKING_AVAILABLE,
	HOMESTAY_BOOKING_UNAVAILABLE,
	HOMESTAY_PENDING_DELETE,
	HOMESTAY_DELETE,
	HOMESTAY_REQUEST_DENIED
}
